#!/usr/bin/env node
/**
 * Disk-first Creator 3.8 preview mirror + HMR.
 *
 * Serve: packer chunks / library / engine cache / snapshotted shell
 * Reload: watch disk → push `browser:reload` (preview-app socket contract)
 *
 * Compile is NOT done here yet — edit TS → Creator/MCP refresh-asset updates
 * packer on disk → this mirror notices → browser reloads.
 *
 * Open without `autoReload=false` to receive reloads:
 *   http://127.0.0.1:7460/
 */
import http from 'http';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { spawn } from 'child_process';
import { WebSocketServer } from 'ws';
import imageImporter from './importers/image.cjs';
import audioImporter from './importers/audio.cjs';
import fontImporter from './importers/font.cjs';
import bmfontImporter from './importers/bmfont.cjs';
import spineImporter from './importers/spine.cjs';
import plistImporter from './importers/plist.cjs';
import textImporter from './importers/text.cjs';
import gltfImporter from './importers/gltf.cjs';
import fbxImporter from './importers/fbx.cjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT || 7460);
const PROJECT = path.resolve(process.env.PROJECT || 'd:/tempWorkspace/baseAIAutoCocos');
const CREATOR = process.env.CREATOR_ROOT || 'C:/ProgramData/cocos/editors/Creator/3.8.8';
const UPSTREAM = process.env.PREVIEW_UPSTREAM || '';
const CACHE = path.join(__dirname, 'cache');
// Engine preview cache. Falls back to a snapshot if set (for Creator-off mode).
const ENGINE_SNAPSHOT = process.env.ENGINE_SNAPSHOT || '';
const ENGINE_PREVIEW = ENGINE_SNAPSHOT
  ? path.join(ENGINE_SNAPSHOT, 'preview')
  : path.join(CREATOR, 'resources/resources/3d/engine/bin/.cache/dev/preview');
const ENGINE_NATIVE_EXT = ENGINE_SNAPSHOT
  ? path.join(ENGINE_SNAPSHOT, 'native-external')
  : path.join(CREATOR, 'resources/resources/3d/engine/native/external');
const PACK_PREVIEW = path.join(PROJECT, 'temp/programming/packer-driver/targets/preview');
// mini-packer output; when present, overlays PACK_PREVIEW for user chunks
const PACK_PREVIEW_MINI = path.join(PROJECT, 'temp/programming/packer-driver/targets/preview-mini');
const LIBRARY = path.join(PROJECT, 'library');
// Engine-internal asset products (internal bundle: effects, default materials,
// builtin textures…). Creator imports these into every project's library/;
// they are project-independent, so we snapshot them once and fall back here
// when the project library (possibly regenerated by our importers) lacks them.
const INTERNAL_LIBRARY = ENGINE_SNAPSHOT ? path.join(ENGINE_SNAPSHOT, 'internal-library') : '';
function libResolve(rel) {
  const own = path.join(LIBRARY, rel);
  if (fs.existsSync(own)) return own;
  if (INTERNAL_LIBRARY) {
    const fallback = path.join(INTERNAL_LIBRARY, rel);
    if (fs.existsSync(fallback)) return fallback;
  }
  return own;
}
const ASSETS = path.join(PROJECT, 'assets');
const EFFECT_BIN = path.join(PROJECT, 'temp/asset-db/effect/effect.bin');
const REQLOG = process.env.REQLOG || path.join(__dirname, 'requests.jsonl');
const WATCH = process.env.WATCH !== '0';
const RELOAD_DEBOUNCE_MS = Number(process.env.RELOAD_DEBOUNCE_MS || 400);
// mini-packer mode: watch assets/*.ts and rebuild via spike/packer/build.cjs
const PACKER = process.env.PACKER || 'creator'; // 'mini' | 'creator'
const MINI_BUILD_SCRIPT = process.env.MINI_BUILD_SCRIPT || path.join(__dirname, 'packer/build.cjs');
const BUILD_DEBOUNCE_MS = Number(process.env.BUILD_DEBOUNCE_MS || 150);
// WATCH_POLL: '0'/unset → native fs.watch only. Any truthy value → also run
// a polling watcher (safe under Docker Desktop bind mounts on Windows/macOS
// where native events don't cross the VM boundary). Poll interval in ms.
const WATCH_POLL = process.env.WATCH_POLL && process.env.WATCH_POLL !== '0';
const WATCH_POLL_MS = Number(process.env.WATCH_POLL_MS || 1000);
const { IMAGE_EXTS, importImage } = imageImporter;
const { AUDIO_EXTS, importAudio } = audioImporter;
const { FONT_EXTS, importFont } = fontImporter;
const { BMFONT_EXTS, importBMFont } = bmfontImporter;
const { importSpine, importSpineBinary, isSpineJson } = spineImporter;
const { PLIST_EXTS, importPlist, parsePlist, classifyPlist } = plistImporter;
const { TEXT_EXTS, importText } = textImporter;
const { GLTF_EXTS, importGltf } = gltfImporter;
const { FBX_EXTS, importFbx } = fbxImporter;

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.wasm': 'application/wasm',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.ico': 'image/x-icon',
  '.bin': 'application/octet-stream',
  '.mp3': 'audio/mpeg',
  '.wav': 'audio/wav',
  '.ogg': 'audio/ogg',
  '.aac': 'audio/aac',
  '.m4a': 'audio/mp4',
  '.ttf': 'font/ttf',
  '.plist': 'text/xml; charset=utf-8',
};

function send(res, status, body, ctype, via) {
  const headers = {
    'Content-Type': ctype || 'text/plain; charset=utf-8',
    'Cache-Control': 'no-store',
    'Access-Control-Allow-Origin': '*',
  };
  if (via) headers['X-Preview-Mirror'] = via;
  res.writeHead(status, headers);
  res.end(body);
}

function sendFile(res, filePath, via) {
  if (!fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) return false;
  const ext = path.extname(filePath).toLowerCase();
  send(res, 200, fs.readFileSync(filePath), MIME[ext] || 'application/octet-stream', via || 'disk');
  return true;
}

function sendMapped(res, mapped) {
  if (!mapped) return false;
  if (typeof mapped === 'string') return sendFile(res, mapped, 'disk');
  if (mapped.rewrite === 'settings') {
    if (!fs.existsSync(mapped.file)) return false;
    const body = rewriteSettings(fs.readFileSync(mapped.file, 'utf8'));
    send(res, 200, body, 'application/javascript; charset=utf-8', 'settings-rewrite');
    return true;
  }
  if (mapped.rewrite === 'main-config') {
    if (!fs.existsSync(mapped.file)) return false;
    const body = rewriteMainConfig(fs.readFileSync(mapped.file, 'utf8'));
    send(res, 200, body, 'application/json; charset=utf-8', 'main-config-rewrite');
    return true;
  }
  if (mapped.rewrite === 'engine-import-map') {
    if (!fs.existsSync(mapped.file)) return false;
    const body = rewriteEngineImportMap(fs.readFileSync(mapped.file, 'utf8'));
    send(res, 200, body, 'application/json; charset=utf-8', 'engine-import-map-rewrite');
    return true;
  }
  if (mapped.rewrite === 'bundle-config') {
    const body = buildBundleConfig(mapped.name, mapped.root);
    send(res, 200, body, 'application/json; charset=utf-8', 'bundle-config-synth');
    return true;
  }
  if (mapped.rewrite === 'bundle-index') {
    send(res, 200, BUNDLE_INDEX_JS(mapped.name), 'application/javascript; charset=utf-8', 'bundle-index-synth');
    return true;
  }
  return false;
}

function safeJoin(root, rel) {
  const full = path.normalize(path.join(root, rel));
  if (!full.startsWith(path.normalize(root))) return null;
  return full;
}

/** Mimics socket.io client enough for preview-app: on('browser:reload') via WS /__hmr */
const SOCKET_IO_STUB = `System.register([], function (_export) {
  return {
    execute: function () {
      function io() {
        var handlers = Object.create(null);
        var proto = location.protocol === 'https:' ? 'wss:' : 'ws:';
        var ws;
        try {
          ws = new WebSocket(proto + '//' + location.host + '/__hmr');
          ws.onmessage = function (ev) {
            var msg;
            try { msg = JSON.parse(ev.data); } catch (e) { return; }
            var list = handlers[msg.event] || [];
            for (var i = 0; i < list.length; i++) list[i].apply(null, msg.args || []);
          };
        } catch (e) {
          console.warn('[preview-mirror] hmr ws failed', e);
        }
        var sock = {
          on: function (event, fn) {
            (handlers[event] || (handlers[event] = [])).push(fn);
            return this;
          },
          emit: function () { return this; },
          off: function (event, fn) {
            if (!handlers[event]) return this;
            if (!fn) { delete handlers[event]; return this; }
            handlers[event] = handlers[event].filter(function (x) { return x !== fn; });
            return this;
          },
          disconnect: function () { try { ws && ws.close(); } catch (e) {} },
        };
        return sock;
      }
      io.default = io;
      if (typeof window !== 'undefined') window.io = io;
      _export('default', io);
    }
  };
});`;

async function proxy(req, res) {
  if (!UPSTREAM) {
    send(res, 404, 'not found: ' + req.url, 'text/plain; charset=utf-8', 'miss');
    return;
  }
  try {
    const url = UPSTREAM.replace(/\/$/, '') + req.url;
    const r = await fetch(url, { headers: { accept: req.headers.accept || '*/*' } });
    const buf = Buffer.from(await r.arrayBuffer());
    res.writeHead(r.status, {
      'Content-Type': r.headers.get('content-type') || 'application/octet-stream',
      'Cache-Control': 'no-store',
      'Access-Control-Allow-Origin': '*',
      'X-Preview-Mirror': 'proxy',
    });
    res.end(buf);
  } catch (e) {
    send(res, 502, 'upstream error: ' + e.message, 'text/plain; charset=utf-8', 'error');
  }
}

function resolveLaunchSceneUuid() {
  // Explicit override: a scene uuid, or a scene name / path fragment to match.
  const forced = process.env.LAUNCH_SCENE;
  if (forced) {
    if (/^[0-9a-fA-F-]{36}$/.test(forced)) return forced;
    try {
      const walk = (dir) => {
        for (const name of fs.readdirSync(dir)) {
          const full = path.join(dir, name);
          const st = fs.statSync(full);
          if (st.isDirectory()) { const hit = walk(full); if (hit) return hit; }
          else if (name.endsWith('.scene.meta')) {
            const rel = path.relative(PROJECT, full).replace(/\\/g, '/');
            if (rel.includes(forced) || name === `${forced}.scene.meta`) {
              const uuid = JSON.parse(fs.readFileSync(full, 'utf8')).uuid;
              if (/^[0-9a-fA-F-]{36}$/.test(uuid)) return uuid;
            }
          }
        }
        return null;
      };
      const hit = walk(path.join(PROJECT, 'assets'));
      if (hit) return hit;
    } catch {}
  }
  const preferred = path.join(PROJECT, 'assets/scene/PreviewBoot.scene.meta');
  if (fs.existsSync(preferred)) {
    try {
      const uuid = JSON.parse(fs.readFileSync(preferred, 'utf8')).uuid;
      if (/^[0-9a-fA-F-]{36}$/.test(uuid)) return uuid;
    } catch {}
  }
  try {
    const walk = (dir) => {
      for (const name of fs.readdirSync(dir)) {
        const full = path.join(dir, name);
        const st = fs.statSync(full);
        if (st.isDirectory()) {
          const hit = walk(full);
          if (hit) return hit;
        } else if (name.endsWith('.scene.meta')) {
          const uuid = JSON.parse(fs.readFileSync(full, 'utf8')).uuid;
          if (/^[0-9a-fA-F-]{36}$/.test(uuid)) return uuid;
        }
      }
      return null;
    };
    return walk(path.join(PROJECT, 'assets'));
  } catch {
    return null;
  }
}

// The cached settings.js was snapshotted from ONE project; every project-
// dependent field (pipeline, modules, design resolution, layers, launch scene)
// must be re-derived from the target PROJECT's settings/v2, or projects with a
// different render pipeline abort at boot (errorID 12109: custom-pipeline
// module not available).
function readProjectSettings() {
  const out = {};
  try {
    const eng = JSON.parse(fs.readFileSync(path.join(PROJECT, 'settings/v2/packages/engine.json'), 'utf8'));
    const walk = (o) => {
      if (!o || typeof o !== 'object') return;
      if (Array.isArray(o.includeModules) && !out.includeModules) out.includeModules = o.includeModules;
      if (o['render-pipeline']?._option && !out.renderPipelineOption) out.renderPipelineOption = o['render-pipeline']._option;
      for (const v of Object.values(o)) if (v && typeof v === 'object') walk(v);
    };
    walk(eng);
    if (eng.macroConfig) out.macros = eng.macroConfig;
  } catch {}
  try {
    const proj = JSON.parse(fs.readFileSync(path.join(PROJECT, 'settings/v2/packages/project.json'), 'utf8'));
    if (proj.general?.designResolution) out.designResolution = proj.general.designResolution;
    if (Array.isArray(proj.layer)) out.layers = proj.layer;
  } catch {}
  return out;
}

function rewriteSettings(js) {
  const m = js.match(/^(window\._CCSettings\s*=\s*)([\s\S]*?);?\s*$/);
  let settings = null;
  let prefix = 'window._CCSettings = ';
  if (m) {
    try { settings = JSON.parse(m[2]); prefix = m[1]; } catch {}
  }
  if (!settings) {
    // Fallback: legacy regex-only launchScene patch.
    const uuid = resolveLaunchSceneUuid();
    if (!uuid) return js;
    return js
      .replace(/"launchScene"\s*:\s*""/, `"launchScene":"${uuid}"`)
      .replace(/"launchScene"\s*:\s*"current_scene"/, `"launchScene":"${uuid}"`);
  }

  const uuid = resolveLaunchSceneUuid();
  if (uuid) settings.launch = { ...settings.launch, launchScene: uuid };

  const ps = readProjectSettings();
  if (ps.includeModules) {
    settings.engine.engineModules = ps.includeModules.slice();
    if (ps.renderPipelineOption === 'custom-pipeline'
        && !settings.engine.engineModules.includes('custom-pipeline-builtin-scripts')) {
      settings.engine.engineModules.push('custom-pipeline-builtin-scripts');
    }
  }
  if (ps.renderPipelineOption) {
    settings.rendering = {
      ...settings.rendering,
      renderPipeline: '',
      customPipeline: ps.renderPipelineOption === 'custom-pipeline',
    };
  }
  if (ps.macros) settings.engine.macros = { ...settings.engine.macros, ...ps.macros };
  if (ps.designResolution) {
    const d = ps.designResolution;
    // ResolutionPolicy: SHOW_ALL=2, FIXED_HEIGHT=3, FIXED_WIDTH=4, NO_BORDER=1
    const policy = d.fitWidth && d.fitHeight ? 2 : d.fitHeight ? 3 : d.fitWidth ? 4 : 1;
    settings.screen = { ...settings.screen, designResolution: { width: d.width, height: d.height, policy } };
  }
  if (ps.layers) {
    settings.engine.customLayers = ps.layers
      .filter((l) => l && l.name && Number.isInteger(Math.log2(l.value)))
      .map((l) => ({ name: l.name, bit: Math.log2(l.value) }));
  }
  const bundles = [...findBundles().keys()];
  if (bundles.length) {
    const known = new Set(settings.assets.projectBundles || []);
    for (const b of bundles) if (!known.has(b)) (settings.assets.projectBundles ||= []).push(b);
    // `resources` is the built-in resources bundle (cc.resources) — Creator
    // always preloads it so `resources.load(...)` works without an explicit
    // loadBundle. Custom bundles stay on-demand.
    if (bundles.includes('resources')) {
      settings.assets.preloadBundles ||= [];
      if (!settings.assets.preloadBundles.some((e) => e && e.bundle === 'resources')) {
        settings.assets.preloadBundles.push({ bundle: 'resources' });
      }
    }
  }
  return prefix + JSON.stringify(settings) + ';';
}

// Serialized-JSON assets that live in library as a straight copy of the source
// file; the string is the runtime asset type used in bundle config `paths`.
const JSON_ASSET_TYPES = {
  '.prefab': 'cc.Prefab',
  '.scene': 'cc.SceneAsset',
  '.anim': 'cc.AnimationClip',
  '.animgraph': 'cc.animation.AnimationGraph',
  '.mtl': 'cc.Material',
};

function collectHeadlessAssets(rootDir = ASSETS) {
  const images = [];
  const audios = [];
  const fonts = [];
  const bmfonts = [];
  const spines = [];
  const atlases = [];
  const particles = [];
  const texts = [];
  const jsonAssets = []; // { uuid, dbPath, rel, type } — prefab/scene/anim/... + cc.JsonAsset
  function walk(dir) {
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      const file = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(file);
        continue;
      }
      const ext = path.extname(entry.name).toLowerCase();
      const isImage = IMAGE_EXTS.has(ext);
      const isAudio = AUDIO_EXTS.has(ext);
      const isFont = FONT_EXTS.has(ext);
      const isBMFont = BMFONT_EXTS.has(ext);
      const isPlist = PLIST_EXTS.has(ext);
      const isText = TEXT_EXTS.has(ext);
      const isJsonAsset = ext in JSON_ASSET_TYPES;
      const maybeSpine = ext === '.json' || ext === '.skel';
      if (!isImage && !isAudio && !isFont && !isBMFont && !isPlist && !isText && !isJsonAsset && !maybeSpine) continue;
      try {
        const meta = JSON.parse(fs.readFileSync(`${file}.meta`, 'utf8'));
        if (!meta.uuid) continue;
        const relFromAssets = path.relative(ASSETS, file).replace(/\\/g, '/');
        const rel = path.relative(rootDir, file).replace(/\\/g, '/').slice(0, -ext.length);
        const dbPath = `db:/assets/${relFromAssets.slice(0, -ext.length)}`;
        if (isPlist) {
          if (meta.importer === 'sprite-atlas') {
            const frames = Object.values(meta.subMetas || {})
              .filter((s) => s && s.uuid && s.importer === 'sprite-frame')
              .map((s) => s.uuid);
            atlases.push({ uuid: meta.uuid, frames, dbPath, rel });
          } else if (meta.importer === 'particle') {
            particles.push({ uuid: meta.uuid, dbPath, rel });
          }
        } else if (isImage) {
          const texture = meta.subMetas?.['6c48a']?.uuid;
          const spriteFrame = meta.subMetas?.['f9941']?.uuid;
          if (!texture || !spriteFrame) continue;
          images.push({ uuid: meta.uuid, texture, spriteFrame, ext, dbPath, rel });
        } else if (isAudio) {
          audios.push({ uuid: meta.uuid, ext, dbPath, rel });
        } else if (isFont) {
          fonts.push({ uuid: meta.uuid, ext, dbPath, rel });
        } else if (isBMFont) {
          if (meta.importer === 'bitmap-font') bmfonts.push({ uuid: meta.uuid, ext, dbPath, rel });
        } else if (isText) {
          texts.push({ uuid: meta.uuid, ext, dbPath, rel });
        } else if (meta.importer === 'spine-data') {
          spines.push({ uuid: meta.uuid, ext, dbPath, rel });
        } else if (isJsonAsset) {
          jsonAssets.push({ uuid: meta.uuid, dbPath, rel, type: JSON_ASSET_TYPES[ext] });
        } else if (ext === '.json' && meta.importer === 'json') {
          jsonAssets.push({ uuid: meta.uuid, dbPath, rel, type: 'cc.JsonAsset' });
        }
      } catch {}
    }
  }
  walk(rootDir);
  return { images, audios, fonts, bmfonts, spines, atlases, particles, texts, jsonAssets };
}

function rewriteMainConfig(json) {
  let config;
  try { config = JSON.parse(json); } catch { return json; }
  config.uuids ||= [];
  config.paths ||= {};
  config.extensionMap ||= {};
  const known = new Set(config.uuids);
  const add = (uuid) => {
    if (!known.has(uuid)) {
      config.uuids.push(uuid);
      known.add(uuid);
    }
  };
  const { images, audios, fonts, bmfonts, spines, atlases, particles, texts } = collectHeadlessAssets();
  for (const image of images) {
    add(image.uuid);
    add(image.texture);
    add(image.spriteFrame);
    config.paths[image.uuid] = [image.dbPath, 'cc.ImageAsset'];
    config.paths[image.texture] = [image.dbPath, 'cc.Texture2D', 1];
    config.paths[image.spriteFrame] = [image.dbPath, 'cc.SpriteFrame', 1];
    // Never add images to extensionMap: the engine copies that ext onto the
    // IMPORT request (url-transformer: `item.ext || info?.extension`), making
    // the browser fetch raw png bytes and deserialize them as JSON. That map
    // exists for special import formats (.cconb) only.
  }
  for (const audio of audios) {
    add(audio.uuid);
    config.paths[audio.uuid] = [audio.dbPath, 'cc.AudioClip'];
  }
  for (const font of fonts) {
    add(font.uuid);
    config.paths[font.uuid] = [font.dbPath, 'cc.TTFFont'];
  }
  for (const bmfont of bmfonts) {
    add(bmfont.uuid);
    config.paths[bmfont.uuid] = [bmfont.dbPath, 'cc.BitmapFont'];
  }
  for (const spine of spines) {
    add(spine.uuid);
    config.paths[spine.uuid] = [spine.dbPath, 'sp.SkeletonData'];
  }
  for (const atlas of atlases) {
    add(atlas.uuid);
    config.paths[atlas.uuid] = [atlas.dbPath, 'cc.SpriteAtlas'];
    for (const frameUuid of atlas.frames) {
      add(frameUuid);
      config.paths[frameUuid] = [atlas.dbPath, 'cc.SpriteFrame', 1];
    }
  }
  for (const particle of particles) {
    add(particle.uuid);
    config.paths[particle.uuid] = [particle.dbPath, 'cc.ParticleAsset'];
  }
  for (const text of texts) {
    add(text.uuid);
    config.paths[text.uuid] = [text.dbPath, 'cc.TextAsset'];
  }
  return JSON.stringify(config);
}

// ---- custom asset bundles (folders whose .meta carries userData.isBundle) ----
//
// loadBundle('<name>') in the engine fetches `assets/<name>/config.json` and
// `assets/<name>/index.js` (downloader.downloadBundle). Import/native requests
// inside the bundle then resolve to `assets/<name>/{import,native}/xx/uuid.*`,
// which our existing library routing already serves for any bundle segment.
// So supporting bundles = discovering them + synthesizing their config.json.
function findBundles() {
  const bundles = new Map(); // name -> { root, dirRel }
  const walk = (dir) => {
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const full = path.join(dir, entry.name);
      try {
        const meta = JSON.parse(fs.readFileSync(`${full}.meta`, 'utf8'));
        if (meta.userData?.isBundle) {
          const name = meta.userData.bundleName || entry.name;
          bundles.set(name, { root: full, dirRel: path.relative(ASSETS, full).replace(/\\/g, '/') });
        }
      } catch {}
      walk(full); // bundles can nest anywhere (e.g. asset_bundles/game_art/ab/prefab)
    }
  };
  walk(ASSETS);
  return bundles;
}

// Bundle config paths must be relative to the bundle root and extension-less,
// exactly like built bundles, so existing `bundle.load('dir/name')` calls in
// project code keep working. Sub-assets carry a third element (isSubAsset).
function buildBundleConfig(name, root) {
  const config = {
    importBase: 'import',
    nativeBase: 'native',
    name,
    deps: [],
    uuids: [],
    paths: {},
    scenes: {},
    packs: {},
    versions: { import: [], native: [] },
    redirect: [],
    debug: true,
    extensionMap: {},
    hasPreloadScript: false,
    dependencyRelationships: {},
  };
  const known = new Set();
  const add = (uuid) => {
    if (!known.has(uuid)) {
      config.uuids.push(uuid);
      known.add(uuid);
    }
  };
  const { images, audios, fonts, bmfonts, spines, atlases, particles, texts, jsonAssets } =
    collectHeadlessAssets(root);
  for (const image of images) {
    add(image.uuid);
    add(image.texture);
    add(image.spriteFrame);
    config.paths[image.uuid] = [image.rel, 'cc.ImageAsset'];
    config.paths[image.texture] = [`${image.rel}/texture`, 'cc.Texture2D', 1];
    config.paths[image.spriteFrame] = [`${image.rel}/spriteFrame`, 'cc.SpriteFrame', 1];
  }
  for (const a of audios) { add(a.uuid); config.paths[a.uuid] = [a.rel, 'cc.AudioClip']; }
  for (const f of fonts) { add(f.uuid); config.paths[f.uuid] = [f.rel, 'cc.TTFFont']; }
  for (const b of bmfonts) { add(b.uuid); config.paths[b.uuid] = [b.rel, 'cc.BitmapFont']; }
  for (const s of spines) { add(s.uuid); config.paths[s.uuid] = [s.rel, 'sp.SkeletonData']; }
  for (const atlas of atlases) {
    add(atlas.uuid);
    config.paths[atlas.uuid] = [atlas.rel, 'cc.SpriteAtlas'];
    for (const frameUuid of atlas.frames) {
      add(frameUuid);
      config.paths[frameUuid] = [atlas.rel, 'cc.SpriteFrame', 1];
    }
  }
  for (const p of particles) { add(p.uuid); config.paths[p.uuid] = [p.rel, 'cc.ParticleAsset']; }
  for (const t of texts) { add(t.uuid); config.paths[t.uuid] = [t.rel, 'cc.TextAsset']; }
  for (const j of jsonAssets) {
    add(j.uuid);
    config.paths[j.uuid] = [j.rel, j.type];
    if (j.type === 'cc.SceneAsset') config.scenes[`db://assets/${path.relative(ASSETS, root).replace(/\\/g, '/')}/${j.rel}.scene`] = j.uuid;
  }
  return JSON.stringify(config);
}

const BUNDLE_INDEX_JS = (name) =>
  `System.register("virtual:///prerequisite-imports/${name}", [], function () {
  "use strict";
  return { setters: [], execute: function () {} };
});
`;

// Creator ships BOTH spine 3.8 and 4.2 runtimes; the active one is a project
// engine-feature setting, not a fixed engine build. The preview engine bundle
// contains both module variants and both wasm — which one runs is decided purely
// by the import-map entries for spine-version.js / spine-instantiate.js. So we
// read the project setting and rewrite those two lines to match, no rebuild.
function detectSpineVersion() {
  const forced = process.env.SPINE_VERSION;
  if (forced === '3.8' || forced === '4.2') return forced;
  try {
    const cfg = JSON.parse(
      fs.readFileSync(path.join(PROJECT, 'settings/v2/packages/engine.json'), 'utf8'),
    );
    // Walk the (key-mangled) settings tree for a `spine` node carrying `_option`.
    let found = null;
    const walk = (o) => {
      if (found || !o || typeof o !== 'object') return;
      for (const [k, v] of Object.entries(o)) {
        if (k === 'spine' && v && typeof v === 'object' && typeof v._option === 'string') {
          const m = v._option.match(/spine-(3\.8|4\.2)/);
          if (m) { found = m[1]; return; }
        }
        if (v && typeof v === 'object') walk(v);
      }
    };
    walk(cfg);
    if (found) return found;
  } catch {}
  return '3.8';
}

// Same story for marionette (AnimationGraph): the bundle ships BOTH the real
// runtime-exports and empty stubs; the import-map picks the stub when the
// project's engine features exclude the `marionette` module. Enabling it is a
// matter of dropping the empty redirect, no rebuild.
function detectEngineModules() {
  const out = new Set();
  try {
    const cfg = JSON.parse(
      fs.readFileSync(path.join(PROJECT, 'settings/v2/packages/engine.json'), 'utf8'),
    );
    const walk = (o) => {
      if (!o || typeof o !== 'object') return;
      if (Array.isArray(o.includeModules)) for (const m of o.includeModules) out.add(m);
      for (const v of Object.values(o)) if (v && typeof v === 'object') walk(v);
    };
    walk(cfg);
  } catch {}
  return out;
}

const MARIONETTE_REDIRECTS = [
  'q-bundled:///fs/cocos/animation/marionette/runtime-exports.js',
  'q-bundled:///fs/cocos/animation/marionette/pose-graph/runtime-exports.js',
];

function rewriteEngineImportMap(json) {
  const ver = detectSpineVersion();
  if (ver !== '3.8') {
    json = json.replace(
      /(spine\/lib\/spine-(?:version|instantiate))-3\.8\.js/g,
      `$1-${ver}.js`,
    );
  }
  const modules = detectEngineModules();
  const marionette = process.env.MARIONETTE === '1' || modules.has('marionette');
  if (marionette) {
    try {
      const map = JSON.parse(json);
      for (const key of MARIONETTE_REDIRECTS) delete map.imports?.[key];
      json = JSON.stringify(map);
    } catch {}
  }
  return json;
}

function mapPath(urlPath) {
  const q = urlPath.indexOf('?');
  const p = q >= 0 ? urlPath.slice(0, q) : urlPath;
  if (p === '/' || p === '/index.html') return path.join(CACHE, 'index.html');
  if (p === '/index.css') return path.join(CACHE, 'index.css');
  if (p === '/favicon.ico') return path.join(CACHE, 'favicon.ico');
  if (p === '/settings.js' || p.startsWith('/settings.js')) return { file: path.join(CACHE, 'settings.js'), rewrite: 'settings' };
  if (p === '/scripting/polyfills/bundle.js') return path.join(CACHE, 'polyfills-bundle.js');
  if (p === '/scripting/systemjs/system.js') return path.join(CACHE, 'systemjs-system.js');
  if (p === '/scripting/import-map-global') return path.join(CACHE, 'import-map-global.json');
  if (p === '/preview-app/index.js') return path.join(CACHE, 'preview-app-index.js');
  if (p === '/preview-app/ui.js') return path.join(CACHE, 'preview-app-ui.js');
  if (p === '/preview-app/main.js') return path.join(CACHE, 'preview-app-main.js');
  if (p.startsWith('/scripting/x/')) {
    const rel = p.slice('/scripting/x/'.length);
    // Overlay chunks/* from mini (user script rebuilds go here).
    // Records/import-map stay from Creator's PACK_PREVIEW because it also indexes
    // engine chunks (`cce:/internal/x/cc`, prerequisite-imports, etc.) that mini
    // doesn't produce. Chunk filenames are hashes of source paths, so mini's
    // fresh HeadlessProbe.ts chunk lands at the same URL Creator's import-map
    // already points to — bytes get replaced transparently.
    if (rel.startsWith('chunks/')) {
      const mini = safeJoin(PACK_PREVIEW_MINI, rel);
      if (mini && fs.existsSync(mini)) return mini;
    }
    return safeJoin(PACK_PREVIEW, rel);
  }
  if (p.startsWith('/scripting/engine/bin/.cache/dev/preview/')) {
    const rel = p.slice('/scripting/engine/bin/.cache/dev/preview/'.length);
    const file = safeJoin(ENGINE_PREVIEW, rel);
    // Swap the spine runtime (3.8 <-> 4.2) to match the project engine setting.
    if (file && rel === 'import-map.json') return { file, rewrite: 'engine-import-map' };
    return file;
  }
  const m = p.match(/^\/scene\/([0-9a-fA-F-]{36}|current_scene)\.json$/);
  if (m) {
    let uuid = m[1];
    if (uuid === 'current_scene') uuid = resolveLaunchSceneUuid() || uuid;
    if (/^[0-9a-fA-F-]{36}$/.test(uuid)) {
      return libResolve(path.join(uuid.slice(0, 2), `${uuid}.json`));
    }
  }
  // Creator preview's UUID downloader serves both imported JSON and native
  // bytes through `/import/` (unlike build output, which uses `/native/`).
  const im = p.match(
    /^\/assets\/(?:general|internal|main|[^/]+)\/import\/([0-9a-fA-F]{2})\/([0-9a-fA-F-]{36}(?:@[0-9a-fA-F]+)*)(\.[a-zA-Z0-9]+)$/,
  );
  if (im) return libResolve(path.join(im[1], im[2] + im[3]));
  const nat = p.match(/^\/assets\/(?:general|internal|main|[^/]+)\/native\/([0-9a-fA-F]{2})\/([0-9a-fA-F-]{36})(.*)$/);
  if (nat) {
    const baseFile = libResolve(path.join(nat[1], nat[2] + nat[3]));
    if (fs.existsSync(baseFile)) return baseFile;
  }
  const bundle = p.match(/^\/assets\/([^/]+)\/(config\.json|index\.js)$/);
  if (bundle) {
    const cached = path.join(CACHE, 'assets', bundle[1], bundle[2]);
    if (fs.existsSync(cached)) {
      if (bundle[1] === 'main' && bundle[2] === 'config.json') {
        return { file: cached, rewrite: 'main-config' };
      }
      return cached;
    }
    // Not in the snapshot cache → a project bundle folder; synthesize.
    const found = findBundles().get(bundle[1]);
    if (found) {
      if (bundle[2] === 'config.json') return { rewrite: 'bundle-config', name: bundle[1], root: found.root };
      return { rewrite: 'bundle-index', name: bundle[1] };
    }
  }
  return null;
}

function queryExtname(uuid) {
  // Mirror engine editor-path-replace semantics: a non-empty answer makes the
  // browser replace `.json` with that ext and STILL deserialize the download
  // as an import JSON. So the only valid non-empty answer is `.cconb` for
  // CCON assets (library holds a single `.bin`). Never return `.png` here —
  // image bytes flow through the asset's native dependency URL instead.
  for (const root of [LIBRARY, INTERNAL_LIBRARY]) {
    if (!root) continue;
    const dir = path.join(root, uuid.slice(0, 2));
    if (!fs.existsSync(dir)) continue;
    const exts = fs
      .readdirSync(dir)
      .filter((f) => f.startsWith(`${uuid}.`))
      .map((f) => f.slice(uuid.length).toLowerCase());
    if (!exts.length) continue;
    if (exts.length === 1 && exts[0] === '.bin') return '.cconb';
    return '';
  }
  return '';
}

// ---- localization-editor extension endpoints ----
//
// Projects using Creator's localization-editor fetch two preview endpoints
// (`/{mainName}/resource-list` and `/{mainName}/resource-bundle`) that the
// extension normally serves from inside Creator. We serve them from the
// extension's on-disk store: {PROJECT}/localization-editor/translate-data/
// <lang>.yaml (index.yaml is the source language, not a translation).
function parseL10nYaml(text) {
  // Minimal parser for the translate-data shape:
  //   items:
  //     - - <key>
  //       - key: <key>
  //         value: '...'
  //         type: N
  const items = [];
  let cur = null;
  for (const line of text.split(/\r?\n/)) {
    const keyM = line.match(/^\s+- - (.+)$/);
    if (keyM) {
      cur = { key: keyM[1].trim(), value: '', type: 0 };
      items.push(cur);
      continue;
    }
    if (!cur) continue;
    const valM = line.match(/^\s+value: (.*)$/);
    if (valM) {
      let v = valM[1].trim();
      if ((v.startsWith("'") && v.endsWith("'")) || (v.startsWith('"') && v.endsWith('"'))) {
        v = v.slice(1, -1).replace(/''/g, "'");
      }
      cur.value = v;
      continue;
    }
    const typeM = line.match(/^\s+type: (\d+)$/);
    if (typeM) cur.type = Number(typeM[1]);
  }
  return items;
}

function l10nDataDir() {
  return path.join(PROJECT, 'localization-editor', 'translate-data');
}

function l10nResourceList() {
  const dir = l10nDataDir();
  let langs = [];
  try {
    langs = fs.readdirSync(dir)
      .filter((f) => f.endsWith('.yaml') && f !== 'index.yaml')
      .map((f) => f.slice(0, -5));
  } catch { return null; }
  let defaultLanguage = langs[0];
  try {
    const cfg = JSON.parse(fs.readFileSync(
      path.join(PROJECT, 'settings/v2/packages/localization-editor.json'), 'utf8'));
    const local = cfg.ProjectConfig?.localLanguage;
    if (local && langs.includes(local)) defaultLanguage = local;
  } catch {}
  return { defaultLanguage, fallbackLanguage: defaultLanguage, languages: langs };
}

function l10nResourceBundle() {
  const list = l10nResourceList();
  if (!list) return null;
  const bundle = {};
  for (const lang of list.languages) {
    const translation = {};
    const asset = {};
    try {
      const items = parseL10nYaml(fs.readFileSync(path.join(l10nDataDir(), `${lang}.yaml`), 'utf8'));
      for (const it of items) {
        // type 1 entries key an asset-uuid override; the rest are text keys.
        if (it.type === 1) asset[it.key] = it.value;
        else translation[it.key] = it.value;
      }
    } catch {}
    bundle[lang] = { translation, asset };
  }
  return bundle;
}

function mapSpecial(urlPath) {
  const u = new URL(urlPath, 'http://127.0.0.1');
  if (u.pathname === '/src/effect.bin') return EFFECT_BIN;
  if (u.pathname === '/engine_external/' || u.pathname === '/engine_external') {
    const raw = u.searchParams.get('url') || '';
    const rel = raw.replace(/^external:/, '');
    if (!rel) return null;
    return safeJoin(ENGINE_NATIVE_EXT, rel);
  }
  return null;
}

const hmrClients = new Set();
let reloadTimer = null;
let reloadSeq = 0;

function broadcastReload(reason) {
  reloadSeq += 1;
  const payload = JSON.stringify({
    event: 'browser:reload',
    args: [],
    reason: reason || 'disk',
    seq: reloadSeq,
    t: Date.now(),
  });
  console.log('[hmr] browser:reload', reason || 'disk', 'clients=' + hmrClients.size, 'seq=' + reloadSeq);
  for (const ws of hmrClients) {
    if (ws.readyState === 1) ws.send(payload);
  }
}

function scheduleReload(reason) {
  clearTimeout(reloadTimer);
  reloadTimer = setTimeout(() => broadcastReload(reason), RELOAD_DEBOUNCE_MS);
}

// ---- mini-packer autobuild ----
let buildTimer = null;
let buildRunning = false;
let buildPending = false;
let buildSeq = 0;
function runMiniBuild(reason) {
  if (buildRunning) {
    buildPending = true;
    return;
  }
  buildRunning = true;
  const t0 = Date.now();
  const seq = ++buildSeq;
  console.log(`[mini] build#${seq} start (${reason})`);
  const child = spawn(process.execPath, [MINI_BUILD_SCRIPT], {
    cwd: path.dirname(MINI_BUILD_SCRIPT),
    stdio: ['ignore', 'pipe', 'pipe'],
    env: { ...process.env, VERBOSE: '' },
  });
  const outBuf = [];
  child.stdout.on('data', (b) => outBuf.push(b));
  child.stderr.on('data', (b) => outBuf.push(b));
  child.on('close', (code) => {
    const ms = Date.now() - t0;
    if (code === 0) {
      console.log(`[mini] build#${seq} ok in ${ms}ms`);
      broadcastReload('mini:' + reason);
    } else {
      const tail = Buffer.concat(outBuf).toString().slice(-800);
      console.error(`[mini] build#${seq} FAILED (code=${code}) in ${ms}ms\n${tail}`);
    }
    buildRunning = false;
    if (buildPending) {
      buildPending = false;
      runMiniBuild('pending');
    }
  });
}
function scheduleMiniBuild(reason) {
  clearTimeout(buildTimer);
  buildTimer = setTimeout(() => runMiniBuild(reason), BUILD_DEBOUNCE_MS);
}

// ---- Mini asset-db: sync JSON-only assets (scene/prefab/anim/mtl…) into library ----
// Creator, for these types, essentially copies the file to library/<xx>/<uuid>.json.
// We replicate that on save so AI can edit assets/*.prefab directly.
const SYNC_EXTS = new Set(['.scene', '.prefab', '.mtl', '.anim', '.animgraph', '.json']);

// A .json may be a Spine export (skeleton.spine version marker) → needs the
// spine importer, not a raw copy. Returns 'spine' | 'sync' | 'skip'.
function classifyJson(absPath) {
  try {
    const parsed = JSON.parse(fs.readFileSync(absPath, 'utf8'));
    if (isSpineJson(parsed)) return { kind: 'spine', parsed };
    // Already-serialized cc asset (has __type__ at the root, or is an array of
    // serialized objects, e.g. hand-authored prefab-ish data) → copy verbatim.
    const root = Array.isArray(parsed) ? parsed[0] : parsed;
    if (root && typeof root === 'object' && typeof root.__type__ === 'string') {
      return { kind: 'sync' };
    }
    // Plain data JSON: Creator's `json` importer wraps it into cc.JsonAsset.
    return { kind: 'json', parsed };
  } catch {
    return { kind: 'skip' };
  }
}

function importJsonAsset(absPath, parsed) {
  const metaPath = absPath + '.meta';
  if (!fs.existsSync(metaPath)) return null;
  let uuid;
  try {
    uuid = JSON.parse(fs.readFileSync(metaPath, 'utf8')).uuid;
  } catch { return null; }
  if (!uuid || !/^[0-9a-fA-F-]{36}$/.test(uuid)) return null;
  const libDir = path.join(LIBRARY, uuid.slice(0, 2));
  const libPath = path.join(libDir, `${uuid}.json`);
  const wrapped = JSON.stringify({
    __type__: 'cc.JsonAsset',
    _name: path.basename(absPath, '.json'),
    _objFlags: 0,
    __editorExtras__: {},
    _native: '',
    json: parsed,
  }, null, 2);
  try {
    fs.mkdirSync(libDir, { recursive: true });
    if (fs.existsSync(libPath) && fs.readFileSync(libPath, 'utf8') === wrapped) {
      return { libPath, changed: false };
    }
    fs.writeFileSync(libPath, wrapped);
    return { libPath, changed: true };
  } catch (e) {
    console.warn('[json-import] failed', absPath, e.message);
    return null;
  }
}

function importSpineLogged(absPath, label, parsed) {
  try {
    const r = path.extname(absPath).toLowerCase() === '.skel'
      ? importSpineBinary(absPath, LIBRARY)
      : importSpine(absPath, LIBRARY, parsed);
    if (r && r.changed.length) {
      console.log('[spine-import]', label, `pages=[${r.pages.join(', ')}]`, `→ ${r.uuid}`);
    }
    return r;
  } catch (err) {
    console.warn('[spine-import] failed', label, err.message);
    return null;
  }
}
function importPlistLogged(absPath, label) {
  try {
    const r = importPlist(absPath, LIBRARY);
    if (r && r.changed.length) {
      if (r.kind === 'sprite-atlas') {
        console.log('[plist-import]', label, `atlas frames=${r.frames.length}`, `→ ${r.uuid}`);
      } else {
        console.log('[plist-import]', label, 'particle', `→ ${r.uuid}`);
      }
    }
    return r;
  } catch (err) {
    console.warn('[plist-import] failed', label, err.message);
    return null;
  }
}
function importGltfLogged(absPath, label) {
  try {
    const r = importGltf(absPath, LIBRARY);
    if (r && r.changed.length) {
      console.log(
        '[gltf-import]',
        label,
        `meshes=${r.meshes.filter(Boolean).length}`,
        `mats=${r.materials.length}`,
        `→ ${r.uuid}`,
      );
    }
    return r;
  } catch (err) {
    console.warn('[gltf-import] failed', label, err.message);
    return null;
  }
}
function importFbxLogged(absPath, label) {
  try {
    const r = importFbx(absPath, LIBRARY);
    if (r && r.changed.length) {
      console.log(
        '[fbx-import]',
        label,
        `meshes=${r.meshes.filter(Boolean).length}`,
        `→ ${r.uuid}`,
      );
    }
    return r;
  } catch (err) {
    console.warn('[fbx-import] failed', label, err.message);
    return null;
  }
}
function syncAssetToLibrary(assetAbsPath) {
  const ext = path.extname(assetAbsPath).toLowerCase();
  if (!SYNC_EXTS.has(ext)) return null;
  const metaPath = assetAbsPath + '.meta';
  if (!fs.existsSync(metaPath)) return null;
  let uuid;
  try {
    uuid = JSON.parse(fs.readFileSync(metaPath, 'utf8')).uuid;
  } catch { return null; }
  if (!uuid || !/^[0-9a-fA-F-]{36}$/.test(uuid)) return null;
  const libDir = path.join(LIBRARY, uuid.slice(0, 2));
  const libPath = path.join(libDir, `${uuid}.json`);
  try {
    fs.mkdirSync(libDir, { recursive: true });
    const src = fs.readFileSync(assetAbsPath);
    // Skip write if identical (avoids fs.watch echo)
    if (fs.existsSync(libPath)) {
      const dst = fs.readFileSync(libPath);
      if (Buffer.compare(src, dst) === 0) return { libPath, changed: false };
    }
    fs.writeFileSync(libPath, src);
    return { libPath, changed: true };
  } catch (e) {
    console.warn('[asset-sync] failed', assetAbsPath, e.message);
    return null;
  }
}
function bootSyncAssets() {
  let synced = 0, skipped = 0, images = 0;
  function walk(dir) {
    let entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of entries) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (IMAGE_EXTS.has(path.extname(e.name).toLowerCase())) {
        try {
          const r = importImage(p, LIBRARY);
          if (r) {
            images++;
            r.changed.length ? synced++ : skipped++;
          }
        } catch (err) {
          console.warn('[image-import] boot failed', path.relative(ASSETS, p), err.message);
        }
      } else if (AUDIO_EXTS.has(path.extname(e.name).toLowerCase())) {
        try {
          const r = importAudio(p, LIBRARY);
          if (r) {
            images++;
            r.changed.length ? synced++ : skipped++;
          }
        } catch (err) {
          console.warn('[audio-import] boot failed', path.relative(ASSETS, p), err.message);
        }
      } else if (FONT_EXTS.has(path.extname(e.name).toLowerCase())) {
        try {
          const r = importFont(p, LIBRARY);
          if (r) {
            images++;
            r.changed.length ? synced++ : skipped++;
          }
        } catch (err) {
          console.warn('[font-import] boot failed', path.relative(ASSETS, p), err.message);
        }
      } else if (BMFONT_EXTS.has(path.extname(e.name).toLowerCase())) {
        try {
          const r = importBMFont(p, LIBRARY);
          if (r) {
            images++;
            r.changed.length ? synced++ : skipped++;
          }
        } catch (err) {
          console.warn('[bmfont-import] boot failed', path.relative(ASSETS, p), err.message);
        }
      } else if (path.extname(e.name).toLowerCase() === '.skel') {
        const r = importSpineLogged(p, path.relative(ASSETS, p));
        if (r) {
          images++;
          r.changed.length ? synced++ : skipped++;
        }
      } else if (PLIST_EXTS.has(path.extname(e.name).toLowerCase())) {
        const r = importPlistLogged(p, path.relative(ASSETS, p));
        if (r) {
          images++;
          r.changed.length ? synced++ : skipped++;
        }
      } else if (GLTF_EXTS.has(path.extname(e.name).toLowerCase())) {
        const r = importGltfLogged(p, path.relative(ASSETS, p));
        if (r) {
          images++;
          r.changed.length ? synced++ : skipped++;
        }
      } else if (FBX_EXTS.has(path.extname(e.name).toLowerCase())) {
        const r = importFbxLogged(p, path.relative(ASSETS, p));
        if (r) {
          images++;
          r.changed.length ? synced++ : skipped++;
        }
      } else if (TEXT_EXTS.has(path.extname(e.name).toLowerCase())) {
        try {
          const r = importText(p, LIBRARY);
          if (r) {
            images++;
            r.changed.length ? synced++ : skipped++;
          }
        } catch (err) {
          console.warn('[text-import] boot failed', path.relative(ASSETS, p), err.message);
        }
      } else if (SYNC_EXTS.has(path.extname(e.name).toLowerCase())) {
        if (path.extname(e.name).toLowerCase() === '.json') {
          const cls = classifyJson(p);
          if (cls.kind === 'spine') {
            const r = importSpineLogged(p, path.relative(ASSETS, p), cls.parsed);
            if (r) {
              images++;
              r.changed.length ? synced++ : skipped++;
            }
            continue;
          }
          if (cls.kind === 'skip') continue;
          if (cls.kind === 'json') {
            const r = importJsonAsset(p, cls.parsed);
            if (r) r.changed ? synced++ : skipped++;
            continue;
          }
        }
        const r = syncAssetToLibrary(p);
        if (r) r.changed ? synced++ : skipped++;
      }
    }
  }
  walk(ASSETS);
  console.log(`[asset-sync] boot: ${synced} written, ${skipped} unchanged, ${images} media asset(s)`);
}

// Directory-mtime-based polling: cheap, catches file adds/removes/renames
// (parent dir mtime bumps on most FSes) and body edits (file mtime bumps).
// Scans are ASYNC and never overlap: on Docker Desktop bind mounts a stat can
// take milliseconds, and a synchronous walk of a few hundred entries would
// block the event loop (and thus every HTTP request) for seconds per tick.
function makePollingWatcher(root, onEvent, opts = {}) {
  const skipRegex = opts.skipRegex || null;
  const isTracked = opts.isTracked || (() => true); // filename filter for events
  const state = new Map(); // absPath → { m, size, isDir }
  async function walk(dir, initial, seen) {
    let entries;
    try { entries = await fs.promises.readdir(dir, { withFileTypes: true }); } catch { return; }
    seen.add(dir);
    try {
      const dm = (await fs.promises.stat(dir)).mtimeMs;
      const prev = state.get(dir);
      state.set(dir, { m: dm, isDir: true });
      if (!initial && (!prev || prev.m !== dm)) {
        onEvent('dir', path.relative(root, dir) || '.');
      }
    } catch {}
    for (const e of entries) {
      const p = path.join(dir, e.name);
      if (skipRegex && skipRegex.test(p)) continue;
      if (e.isDirectory()) {
        await walk(p, initial, seen);
      } else {
        let stat;
        try { stat = await fs.promises.stat(p); } catch { continue; }
        seen.add(p);
        const prev = state.get(p);
        state.set(p, { m: stat.mtimeMs, size: stat.size, isDir: false });
        if (!initial && (!prev || prev.m !== stat.mtimeMs || prev.size !== stat.size)) {
          if (isTracked(e.name)) onEvent('file', path.relative(root, p));
        }
      }
    }
  }
  async function scan(initial) {
    const seen = new Set();
    await walk(root, initial, seen);
    // Remove vanished paths from the snapshot. Without this, a directory that
    // is deleted and recreated between two polls can keep stale file entries,
    // so copying the same fixture back may never emit an add event.
    for (const [p, previous] of state) {
      if (seen.has(p)) continue;
      state.delete(p);
      if (!initial && !previous.isDir && isTracked(path.basename(p))) {
        onEvent('delete', path.relative(root, p));
      }
    }
  }
  let stopped = false;
  let timer = null;
  const tick = () => {
    if (stopped) return;
    scan(false)
      .catch(() => {})
      .finally(() => {
        if (!stopped) {
          timer = setTimeout(tick, WATCH_POLL_MS);
          timer.unref();
        }
      });
  };
  scan(true)
    .catch(() => {})
    .finally(() => {
      if (!stopped) {
        timer = setTimeout(tick, WATCH_POLL_MS);
        timer.unref();
      }
    });
  return {
    stop: () => {
      stopped = true;
      if (timer) clearTimeout(timer);
    },
  };
}

function watchTree(root, label) {
  if (!fs.existsSync(root)) {
    console.log('[hmr] skip missing', label, root);
    return;
  }
  const handler = (name) => {
    if (name.endsWith('.meta.tmp') || name.endsWith('~') || name.includes('.git')) return;
    scheduleReload(label + (name ? ':' + name : ''));
  };
  try {
    const w = fs.watch(root, { recursive: true }, (_event, filename) => {
      handler(filename ? String(filename) : '');
    });
    w.on('error', (e) => console.warn('[hmr] watch error', label, e.message));
    console.log('[hmr] watching', label, root, WATCH_POLL ? '(+poll)' : '');
  } catch (e) {
    console.warn('[hmr] cannot watch', label, e.message);
  }
  if (WATCH_POLL) {
    makePollingWatcher(root, (_kind, rel) => handler(rel), {
      skipRegex: /\.git|\.meta\.tmp$|~$/,
    });
  }
}

const server = http.createServer(async (req, res) => {
  const urlPath = decodeURIComponent(req.url || '/');
  console.log(req.method, urlPath);
  const _start = Date.now();
  const _origEnd = res.end.bind(res);
  res.end = function (...args) {
    try {
      fs.appendFileSync(
        REQLOG,
        JSON.stringify({
          t: Date.now(),
          ms: Date.now() - _start,
          method: req.method,
          url: urlPath,
          status: res.statusCode,
          via: res.getHeader && res.getHeader('X-Preview-Mirror'),
        }) + '\n'
      );
    } catch {}
    return _origEnd(...args);
  };

  if (urlPath.startsWith('/socket.io/socket.io.js')) {
    send(res, 200, SOCKET_IO_STUB, 'application/javascript; charset=utf-8', 'hmr-stub');
    return;
  }

  // Manual trigger: curl -X POST http://127.0.0.1:7460/__reload
  if (urlPath === '/__reload' || urlPath.startsWith('/__reload?')) {
    broadcastReload('manual');
    send(res, 200, JSON.stringify({ ok: true, clients: hmrClients.size, seq: reloadSeq }), 'application/json; charset=utf-8', 'hmr');
    return;
  }
  if (urlPath === '/__hmr/status') {
    send(
      res,
      200,
      JSON.stringify({ clients: hmrClients.size, seq: reloadSeq, watch: WATCH }),
      'application/json; charset=utf-8',
      'hmr'
    );
    return;
  }

  const qe = urlPath.match(/^\/query-extname\/([0-9a-fA-F-]{36}(?:@[0-9a-fA-F]+)*)\/?$/);
  if (qe) {
    send(res, 200, queryExtname(qe[1]), 'text/plain; charset=utf-8', 'disk');
    return;
  }
  if (urlPath === '/localization-editor/resource-list') {
    const list = l10nResourceList();
    if (list) {
      send(res, 200, JSON.stringify(list), 'application/json; charset=utf-8', 'l10n');
      return;
    }
  }
  if (urlPath === '/localization-editor/resource-bundle') {
    const bundle = l10nResourceBundle();
    if (bundle) {
      send(res, 200, JSON.stringify(bundle), 'application/json; charset=utf-8', 'l10n');
      return;
    }
  }
  const special = mapSpecial(urlPath);
  if (special && sendFile(res, special, 'disk')) return;
  const mapped = mapPath(urlPath);
  if (sendMapped(res, mapped)) return;
  await proxy(req, res);
});

const wss = new WebSocketServer({ noServer: true });
server.on('upgrade', (req, socket, head) => {
  const u = new URL(req.url || '/', 'http://127.0.0.1');
  if (u.pathname !== '/__hmr') {
    socket.destroy();
    return;
  }
  wss.handleUpgrade(req, socket, head, (ws) => {
    hmrClients.add(ws);
    console.log('[hmr] client + now=' + hmrClients.size);
    ws.send(JSON.stringify({ event: 'hmr:hello', args: [{ seq: reloadSeq }] }));
    ws.on('close', () => {
      hmrClients.delete(ws);
      console.log('[hmr] client - now=' + hmrClients.size);
    });
  });
});

server.listen(PORT, () => {
  console.log('[preview-mirror] http://127.0.0.1:' + PORT);
  console.log('  PROJECT=' + PROJECT);
  console.log('  PACK=' + PACK_PREVIEW);
  console.log('  ENGINE=' + ENGINE_PREVIEW);
  console.log('  UPSTREAM=' + (UPSTREAM || '(none)'));
  console.log('  HMR=ws://127.0.0.1:' + PORT + '/__hmr  (open WITHOUT autoReload=false)');
  if (WATCH) {
    if (PACKER === 'mini') {
      // Headless mode: don't reload directly on packer/asset-db (Creator's outputs
      // — we own them). Watch source files, run mini-build, reload on success.
      console.log('[mini] mode=on script=' + MINI_BUILD_SCRIPT);
      watchTree(LIBRARY, 'library'); // library changes → HMR reload
      // Custom watcher on assets: TS/JS → mini-build; JSON assets → sync to library
      const onAssetChange = (name) => {
        if (!name) return;
        if (/\.d\.ts$/.test(name)) return;
        if (/\.(ts|js)$/.test(name)) {
          scheduleMiniBuild(name);
          return;
        }
        const rel = name.replace(/\.meta$/, '');
        const ext = path.extname(rel).toLowerCase();
        if (IMAGE_EXTS.has(ext)) {
          const abs = path.join(ASSETS, rel);
          if (!fs.existsSync(abs)) return;
          try {
            const r = importImage(abs, LIBRARY);
            if (r && r.changed.length) {
              console.log(
                '[image-import]',
                rel,
                `${r.width}x${r.height}`,
                `→ ${r.spriteFrameUuid}`,
              );
            }
          } catch (err) {
            console.warn('[image-import] failed', rel, err.message);
          }
          return;
        }
        if (AUDIO_EXTS.has(ext)) {
          const abs = path.join(ASSETS, rel);
          if (!fs.existsSync(abs)) return;
          try {
            const r = importAudio(abs, LIBRARY);
            if (r && r.changed.length) {
              console.log('[audio-import]', rel, `→ ${r.uuid}${r.ext}`);
            }
          } catch (err) {
            console.warn('[audio-import] failed', rel, err.message);
          }
          return;
        }
        if (FONT_EXTS.has(ext)) {
          const abs = path.join(ASSETS, rel);
          if (!fs.existsSync(abs)) return;
          try {
            const r = importFont(abs, LIBRARY);
            if (r && r.changed.length) {
              console.log('[font-import]', rel, `→ ${r.uuid}/${r.nativeName}`);
            }
          } catch (err) {
            console.warn('[font-import] failed', rel, err.message);
          }
          return;
        }
        if (BMFONT_EXTS.has(ext)) {
          const abs = path.join(ASSETS, rel);
          if (!fs.existsSync(abs)) return;
          try {
            const r = importBMFont(abs, LIBRARY);
            if (r && r.changed.length) {
              console.log('[bmfont-import]', rel, `chars=${r.chars}`, `→ ${r.uuid}`);
            }
          } catch (err) {
            console.warn('[bmfont-import] failed', rel, err.message);
          }
          return;
        }
        if (ext === '.atlas') {
          // Spine atlas edit → re-import the sibling .json or .skel skeleton.
          const base = path.join(ASSETS, rel).slice(0, -'.atlas'.length);
          const sibling = fs.existsSync(`${base}.json`) ? `${base}.json` : `${base}.skel`;
          if (fs.existsSync(sibling)) importSpineLogged(sibling, rel);
          return;
        }
        if (ext === '.skel') {
          const abs = path.join(ASSETS, rel);
          if (fs.existsSync(abs)) importSpineLogged(abs, rel);
          return;
        }
        if (PLIST_EXTS.has(ext)) {
          const abs = path.join(ASSETS, rel);
          if (fs.existsSync(abs)) importPlistLogged(abs, rel);
          return;
        }
        if (GLTF_EXTS.has(ext)) {
          const abs = path.join(ASSETS, rel);
          if (fs.existsSync(abs)) importGltfLogged(abs, rel);
          return;
        }
        if (FBX_EXTS.has(ext)) {
          const abs = path.join(ASSETS, rel);
          if (fs.existsSync(abs)) importFbxLogged(abs, rel);
          return;
        }
        if (TEXT_EXTS.has(ext)) {
          const abs = path.join(ASSETS, rel);
          if (!fs.existsSync(abs)) return;
          try {
            const r = importText(abs, LIBRARY);
            if (r && r.changed.length) console.log('[text-import]', rel, `→ ${r.uuid}`);
          } catch (err) {
            console.warn('[text-import] failed', rel, err.message);
          }
          return;
        }
        if (SYNC_EXTS.has(ext)) {
          const abs = path.join(ASSETS, rel);
          if (ext === '.json' && fs.existsSync(abs)) {
            const cls = classifyJson(abs);
            if (cls.kind === 'spine') {
              importSpineLogged(abs, rel, cls.parsed);
              return;
            }
            if (cls.kind === 'skip') return;
            if (cls.kind === 'json') {
              const r = importJsonAsset(abs, cls.parsed);
              if (r && r.changed) console.log('[json-import]', rel, '→', path.relative(PROJECT, r.libPath));
              return;
            }
          }
          const r = syncAssetToLibrary(abs);
          if (r && r.changed) console.log('[asset-sync]', rel, '→', path.relative(PROJECT, r.libPath));
        }
      };
      try {
        const w = fs.watch(ASSETS, { recursive: true }, (_e, fn) => {
          onAssetChange(fn ? String(fn) : '');
        });
        w.on('error', (e) => console.warn('[mini] watch error', e.message));
        console.log('[mini] watching', ASSETS, WATCH_POLL ? '(+poll)' : '');
      } catch (e) {
        console.warn('[mini] cannot watch assets', e.message);
      }
      if (WATCH_POLL) {
        makePollingWatcher(ASSETS, (_kind, rel) => onAssetChange(rel), {
          skipRegex: /\.git|\.meta\.tmp$|~$/,
          isTracked: (name) => /\.(ts|js|meta|scene|prefab|mtl|anim|animgraph|json|skel|png|jpe?g|mp3|wav|ogg|aac|m4a|ttf|fnt|atlas|plist|txt|csv|ya?ml|conf|md|gltf|glb|fbx)$/i.test(name),
        });
      }
      // Prime: sync all JSON assets once, then build scripts once
      bootSyncAssets();
      runMiniBuild('boot');
    } else {
      // Creator mode: react to whatever Creator writes to disk
      watchTree(PACK_PREVIEW, 'packer');
      watchTree(LIBRARY, 'library');
      watchTree(path.join(PROJECT, 'temp/asset-db'), 'asset-db');
      watchTree(ASSETS, 'assets');
    }
  } else {
    console.log('[hmr] WATCH=0 — only POST /__reload');
  }
});
