import {
  type BindConfig,
  type BindNodeEntry,
  viewClassToBindingsName,
} from "./BindJsonManager.ts";
import { type ParsedPrefab } from "../parsers/PrefabParser.ts";
import { type ComponentTypeInfo, lookupComponentType } from "../parsers/ComponentTypeMap.ts";

export interface GenerateOptions {
  /** 工具版本号（写入文件头部注释） */
  toolVersion?: string;
  /** 额外提示要不要把根节点也算上（影响节点路径解析方式） */
  emitRuntimeAssertions?: boolean;
  /** 显式 bind.json 路径，用于头部注释；不传则按 prefab 同名 .bind.json 推导 */
  bindRelativePath?: string;
}

/**
 * 综合查询组件类型：先查内置，再回落到 parsed.allComponents 里 ScriptTypeRegistry 写入的 typeInfo。
 * 把这个查询独立成函数，让 generator 的三处调用点共享同一份逻辑。
 */
function makeTypeResolver(parsed: ParsedPrefab): (rawType: string) => ComponentTypeInfo | undefined {
  // 先把 parsed 中所有 (rawType → typeInfo) 收集到 map（resolve 阶段已经写入 typeInfo）
  const customMap = new Map<string, ComponentTypeInfo>();
  for (const c of parsed.allComponents) {
    if (c.typeInfo && !c.typeInfo.builtin) {
      customMap.set(c.rawType, c.typeInfo);
    }
  }
  return (rawType: string): ComponentTypeInfo | undefined => {
    const builtin = lookupComponentType(rawType);
    if (builtin) return builtin;
    return customMap.get(rawType);
  };
}

/**
 * 判断该组件是否需要为它生成 onClick 钩子：
 *  · cc.Button 内置 → 是
 *  · 其它 isButton=true 的自定义脚本（即 Button 子类）→ 是
 */
function isButtonLikeComponent(info: ComponentTypeInfo): boolean {
  if (info.builtin) return info.tsName === "Button";
  return info.isButton === true;
}

/**
 * 由字段名生成 onClick 方法名：
 *   confirmBtn → onClickConfirmBtn
 *   info/bet 这种已经在 entry.field 阶段 camel 化为 infoBet → onClickInfoBet
 */
function onClickMethodName(field: string): string {
  if (!field) return "onClick";
  return "onClick" + field.charAt(0).toUpperCase() + field.slice(1);
}

/**
 * 把 BindConfig + ParsedPrefab 渲染为 PrefabView 的 .gen.ts 代码。
 *
 * 生成的代码原则：
 * - 文件顶部带「禁止手改」标记；
 * - 一个继承自 cc.Component 的 PrefabView 类；
 * - `bind(root: Node)` 方法：传入运行时 prefab 实例化后的根 Node，
 *   按 path 遍历 children 取出节点和组件并写到 readonly 字段；
 * - 每个 path 都做防御性检查（DEV 下 `assert`）；
 * - 字段全部使用 `readonly`，绑定阶段通过 `(this as any)` 写入。
 *
 * 不做任何运行时反射或字符串拼接 path：路径在生成时就硬编码到代码里。
 */
export function generateGenTs(
  config: BindConfig,
  parsed: ParsedPrefab,
  opts: GenerateOptions = {}
): string {
  const lines: string[] = [];
  const importsFromCc = new Set<string>(["Component", "Node", "_decorator"]);
  const importsFromSp = new Set<string>();
  /** 自定义脚本命名导出：相对路径 → Set<className> */
  const customNamedImports = new Map<string, Set<string>>();
  /** 自定义脚本 default 导出：相对路径 → 类名（一对一） */
  const customDefaultImports = new Map<string, string>();

  const resolveType = makeTypeResolver(parsed);

  /**
   * 预先把每个 entry 上的"按钮组件"挑出来，确定 onClick 方法名 / 用于 bind() 时的字段。
   * 一个 entry 通常只挂一个 cc.Button（或 Button 子类），所以一般每个 entry 顶多 1 项。
   */
  type ButtonHook = {
    /** view 里的字段名（例如 "confirmBtn"） */
    field: string;
    /** 钩子方法名（例如 "onClickConfirmBtn"） */
    method: string;
    /** 为生成更精确注释，挂的是哪个类 */
    typeName: string;
  };
  const buttonHooksPerEntry = new Map<BindNodeEntry, ButtonHook[]>();
  let needButtonImport = false;

  // 收集所有要 import 的类型
  for (const entry of config.nodes) {
    const hooks: ButtonHook[] = [];
    for (const comp of entry.components ?? []) {
      const info = resolveType(comp.rawType);
      if (!info) continue;
      if (info.importFrom === "cc") {
        // info.tsName 形如 "animation.AnimationController" 时，import 顶层名
        const top = info.tsName.split(".")[0];
        importsFromCc.add(top);
      } else if (info.importFrom === "sp") {
        importsFromSp.add("sp");
      } else if (!info.builtin) {
        if (info.isDefaultExport) {
          customDefaultImports.set(info.importFrom, info.tsName);
        } else {
          let set = customNamedImports.get(info.importFrom);
          if (!set) {
            set = new Set();
            customNamedImports.set(info.importFrom, set);
          }
          set.add(info.tsName);
        }
      }
      if (isButtonLikeComponent(info)) {
        const fieldName = comp.field ?? defaultCompFieldName(entry.field, info.tsName);
        hooks.push({
          field: fieldName,
          method: onClickMethodName(fieldName),
          typeName: info.tsName,
        });
        needButtonImport = true;
      }
    }
    if (hooks.length > 0) buttonHooksPerEntry.set(entry, hooks);
  }
  if (needButtonImport) {
    // 即使该 prefab 只用了 Button 子类，事件绑定也走 Button.EventType.CLICK，需要导入 Button
    importsFromCc.add("Button");
  }

  // -------- 文件头 --------
  const bindHeaderPath = opts.bindRelativePath ?? config.prefab.replace(/\.prefab$/, ".bind.json");
  lines.push(
    "// =====================================================================",
    "//  THIS FILE IS AUTO-GENERATED by ViewWeaver. DO NOT EDIT BY HAND.",
    "//",
    `//  source prefab : ${config.prefab}`,
    `//  bind config   : ${bindHeaderPath}`,
    `//  generated at  : ${new Date().toISOString()}`,
    `//  tool version  : ${opts.toolVersion ?? "0.1.0"}`,
    "//",
    "//  To change exposed nodes/components, edit the .bind.json file or use",
    "//  the ViewWeaver editor panel, then re-run ViewWeaver.",
    "// =====================================================================",
    ""
  );

  // -------- imports --------
  const ccList = Array.from(importsFromCc).sort();
  lines.push(`import { ${ccList.join(", ")} } from "cc";`);
  if (importsFromSp.size > 0) {
    lines.push(`import { sp } from "cc";`);
  }
  // IView 契约：所有 ViewWeaver 生成的 view 都必须 implements 它。
  // 路径相对于 .gen.ts —— 当前固定为 `views/<prefab>/<name>.gen.ts`，
  // 所以从这个位置看 IView.ts 就是上一级目录。如果未来 ProjectLayout
  // 改了输出布局，要把这条路径也跟着调（最直接的做法是把它做成 layout 的字段）。
  lines.push(`import type { IView } from "../IView";`);
  // 自定义脚本：合并 default + named，按相对路径排序输出
  const customPaths = new Set<string>([
    ...customNamedImports.keys(),
    ...customDefaultImports.keys(),
  ]);
  for (const p of Array.from(customPaths).sort()) {
    const def = customDefaultImports.get(p);
    const named = Array.from(customNamedImports.get(p) ?? []).sort();
    let stmt = "import ";
    if (def && named.length > 0) {
      stmt += `${def}, { ${named.join(", ")} }`;
    } else if (def) {
      stmt += def;
    } else {
      stmt += `{ ${named.join(", ")} }`;
    }
    stmt += ` from ${JSON.stringify(p)};`;
    lines.push(stmt);
  }
  lines.push("");

  // -------- 节点路径常量（便于 debug） --------
  lines.push("/** 该 PrefabView 绑定的所有节点路径（相对根节点） */");
  lines.push("export const NODE_PATHS = {");
  for (const entry of config.nodes) {
    lines.push(`  ${entry.field}: ${JSON.stringify(entry.path)},`);
  }
  lines.push("} as const;");
  lines.push("");

  // -------- PrefabView 类 --------
  // gen.ts 里只放"内部基类"（下划线前缀 = 自动生成），再由开发者持有的 view.ts 继承它。
  // 这样既保证 onClickXxx 钩子可以通过子类 override，也保证 gen.ts 是 100% 可重新生成的。
  const viewClass = config.viewClassName;
  const bindingsClass = viewClassToBindingsName(viewClass);
  lines.push(`const { ccclass } = _decorator;`);
  lines.push("");
  lines.push(`/**`);
  lines.push(` * ${viewClass} 的自动生成基类（不要直接 @ccclass 挂到节点上，请用 ${viewClass}）。`);
  lines.push(` *`);
  lines.push(` * 字段 / bind() / onClickXxx 钩子均由 ViewWeaver 自动生成；`);
  lines.push(` * 业务逻辑请在 ${viewClass}.ts 里 override 对应钩子。`);
  lines.push(` *`);
  lines.push(` * 实现 IView 契约 —— 编译期保证 bind(root: Node) 签名稳定，让消费侧（Presenter / Tester）`);
  lines.push(` * 不再依赖 duck typing。bind 的具体实现由 ViewWeaver 注入到下面。`);
  lines.push(` */`);
  lines.push(`@ccclass("${bindingsClass}")`);
  lines.push(`export class ${bindingsClass} extends Component implements IView {`);

  // 字段
  for (const entry of config.nodes) {
    if (entry.exposeNode !== false) {
      const cmt = entry.comment ? `  /** ${escapeComment(entry.comment)} */\n` : "";
      lines.push(`${cmt}  public readonly ${entry.field}!: Node;`);
    }
    for (const comp of entry.components ?? []) {
      const info = resolveType(comp.rawType);
      if (!info) continue;
      const fieldName = comp.field ?? defaultCompFieldName(entry.field, info.tsName);
      const cmt = comp.comment ? `  /** ${escapeComment(comp.comment)} */\n` : "";
      lines.push(`${cmt}  public readonly ${fieldName}!: ${info.tsName};`);
    }
  }
  lines.push("");

  // bind 方法
  lines.push(
    "  /**",
    "   * 把运行时 prefab 实例化出的 root Node 绑定到本 View。",
    "   * - 路径在生成期固化，运行时不做字符串拼接；",
    `   * - 任意 path 找不到节点时，DEV 模式抛错，Release 仅 console.warn；`,
    "   * - 自动注册所有 Button / Button 子类 的 click 事件，路由到本类的 onClickXxx 钩子。",
    "   */",
    "  public bind(root: Node): this {",
    "    const w = this as any;",
    `    w.__root__ = root;`
  );

  for (const entry of config.nodes) {
    const nodeExpr = nodeAccessExpression("root", entry.path);
    const safeNodeVar = `n_${entry.field}`;
    if (entry.path === "") {
      lines.push(`    const ${safeNodeVar} = root;`);
    } else {
      lines.push(`    const ${safeNodeVar} = ${nodeExpr};`);
      lines.push(
        `    if (!${safeNodeVar}) { _viewMissing(${JSON.stringify(entry.path)}); }`
      );
    }
    if (entry.exposeNode !== false) {
      lines.push(`    w.${entry.field} = ${safeNodeVar};`);
    }
    for (const comp of entry.components ?? []) {
      const info = resolveType(comp.rawType);
      if (!info) continue;
      const fieldName = comp.field ?? defaultCompFieldName(entry.field, info.tsName);
      const idx = comp.index ?? 0;
      if (idx === 0) {
        lines.push(
          `    w.${fieldName} = ${safeNodeVar}?.getComponent(${info.tsName});`
        );
      } else {
        lines.push(
          `    {`,
          `      const _all = ${safeNodeVar}?.getComponents(${info.tsName}) ?? [];`,
          `      w.${fieldName} = _all[${idx}];`,
          `    }`
        );
      }
      lines.push(
        `    if (!w.${fieldName}) { _viewMissing(${JSON.stringify(
          entry.path + "::" + info.tsName + (idx > 0 ? `#${idx}` : "")
        )}); }`
      );
    }
    // 注册按钮 click → onClickXxx 钩子
    const hooks = buttonHooksPerEntry.get(entry);
    if (hooks && hooks.length > 0) {
      for (const h of hooks) {
        // 通过 w[method] 动态查表：保证子类 override 后能拿到最新实现，
        // 同时避免 TS 在父类里直接 this.onClickXxx 时被 readonly 字段类型干扰。
        lines.push(
          `    if (w.${h.field}) { w.${h.field}.node.on(Button.EventType.CLICK, w.${h.method}, w); }`
        );
      }
    }
  }
  lines.push("    return this;", "  }");

  // ---- onClick 钩子方法（默认空实现，view.ts 里 override）----
  // 把所有钩子集中放在 bind() 之后，便于阅读"业务侧要 override 的接口"。
  for (const entry of config.nodes) {
    const hooks = buttonHooksPerEntry.get(entry);
    if (!hooks) continue;
    for (const h of hooks) {
      lines.push("");
      lines.push(`  /** 默认空实现；在 ${viewClass}.ts 里 override 即可写业务 */`);
      lines.push(`  protected ${h.method}(): void {}`);
    }
  }

  lines.push("}");
  lines.push("");

  // 公共 helper：缺失警告（一处定义，便于热点 patch）
  lines.push(
    "function _viewMissing(what: string): void {",
    "  // DEV 模式下抛错，便于早暴；Release 下只警告，避免影响线上",
    "  // eslint-disable-next-line no-undef",
    `  const isDev = (typeof globalThis !== "undefined") && ((globalThis as any).CC_DEV || (globalThis as any).DEBUG);`,
    "  const msg = `[viewweaver] missing binding: ${what}`;",
    "  if (isDev) { throw new Error(msg); }",
    "  // eslint-disable-next-line no-console",
    "  console.warn(msg);",
    "}",
    ""
  );

  // 同名 prefab/path 数据元信息（可选，便于工具反查）
  lines.push(
    "export const __viewweaver_meta__ = {",
    `  prefab: ${JSON.stringify(config.prefab)},`,
    `  prefabName: ${JSON.stringify(config.prefabName)},`,
    `  totalNodes: ${parsed.stats.totalNodes},`,
    `  totalComponents: ${parsed.stats.totalComponents},`,
    `  exportedNodeCount: ${config.nodes.length},`,
    "} as const;",
    ""
  );

  return lines.join("\n");
}

function escapeComment(s: string): string {
  return s.replace(/\*\//g, "*\\/").replace(/[\r\n]+/g, " ");
}

function defaultCompFieldName(nodeField: string, tsName: string): string {
  const sanitized = tsName.replace(/[^A-Za-z0-9_]/g, "_");
  return `${nodeField}_${sanitized}`;
}

/**
 * 生成访问节点的链式表达式：
 *   "" → root
 *   "a" → root.getChildByPath("a")     // 单段也可以直接 getChildByName，但用 getChildByPath 更稳
 *   "a/b/c" → root.getChildByPath("a/b/c")
 *
 * 这里只用 getChildByPath，避免拼接错带来歧义；同名兄弟通过 bind.json 用 (1)/(2) 区分时，
 * 实际运行时仍依赖 getChildByPath，因此我们这里用 cocos 不直接支持的 (N) 语法时
 * 退化为索引访问（todo: v0.2 处理同名兄弟）。
 */
function nodeAccessExpression(rootVar: string, path: string): string {
  if (!path) return rootVar;

  // 简单情况：path 不含 "(" 同名兄弟修饰 → 直接 getChildByPath
  if (!/\(\d+\)/.test(path)) {
    return `${rootVar}.getChildByPath(${JSON.stringify(path)})`;
  }

  // 同名兄弟：path 段如 "name(2)"。逐段用 children[索引] 访问。
  const segs = path.split("/").map((seg) => {
    const m = /^(.*)\((\d+)\)$/.exec(seg);
    if (!m) return { name: seg, index: 0 };
    return { name: m[1], index: parseInt(m[2], 10) };
  });

  const tmps: string[] = [];
  let cursor = rootVar;
  for (let i = 0; i < segs.length; i++) {
    const s = segs[i];
    const next = `n${i}`;
    tmps.push(
      `(() => { const _ch = ${cursor}.children.filter(n => n.name === ${JSON.stringify(
        s.name
      )}); return _ch[${s.index}]; })()`
    );
    cursor = next;
  }

  // 把 IIFE 链合成单个表达式。为了简单这里直接嵌套：
  let expr = `${rootVar}`;
  for (const s of segs) {
    expr = `((__p) => __p ? __p.children.filter(n => n.name === ${JSON.stringify(
      s.name
    )})[${s.index}] : undefined)(${expr})`;
  }
  return expr;
}
