/**
 * View.ts 生成器（"一次性"，开发者可改）
 *
 * 与 gen.ts 关系：
 *  - gen.ts 由 ViewWeaver 全权拥有，每次生成都重写。包含字段、bind()、onClickXxx 默认空实现。
 *  - view.ts **只在不存在时**生成一次骨架，落到磁盘后由开发者维护。承自 gen.ts 内部基类。
 *
 * 这个生成器只输出"骨架字符串"，是否要写盘 / 是否覆盖由调用方（runOnce / 编辑器）决定。
 * 我们把"判断文件是否存在"留给上层，是为了便于在测试和 dry-run 流程里复用同一份字符串渲染逻辑。
 */

import * as path from "node:path";

import {
  type BindConfig,
  viewClassToBindingsName,
} from "./BindJsonManager.ts";

export interface GenerateViewOptions {
  /** 工具版本号（写入文件头部注释） */
  toolVersion?: string;
  /**
   * gen.ts 文件相对 view.ts 的 import 路径（不带 .ts 扩展，需带 ./）。
   * 缺省按"同目录、文件名 = `<prefabName>.gen`"推导。
   */
  genTsImportPath?: string;
  /** 用于头部注释的 prefab 路径，缺省取 config.prefab */
  prefabHeaderPath?: string;
}

/**
 * 渲染 view.ts 的初始内容。
 *
 * 设计要点：
 *  · 不在这里枚举具体的 onClickXxx —— 它们在 gen.ts 里有空实现，view.ts 想 override 哪个就写哪个；
 *  · 留下清晰的"override 例子注释"，避免开发者第一次打开文件时手足无措；
 *  · 文件头加 "可手改" 标签（与 gen.ts 头形成对照），让人一眼分清两个文件的所有权。
 */
export function generateViewTs(
  config: BindConfig,
  opts: GenerateViewOptions = {}
): string {
  const viewClass = config.viewClassName;
  const bindingsClass = viewClassToBindingsName(viewClass);
  const importPath = opts.genTsImportPath ?? `./${config.prefabName}.gen`;
  const prefabHeader = opts.prefabHeaderPath ?? config.prefab;

  const lines: string[] = [];
  lines.push(
    "// =====================================================================",
    "//  generated by ViewWeaver - first time only.",
    "//  THIS FILE IS YOURS TO EDIT. ViewWeaver will NOT overwrite it.",
    "//",
    `//  source prefab : ${prefabHeader}`,
    `//  bindings base : ${bindingsClass} (in ${path.basename(importPath)}.ts)`,
    `//  generated at  : ${new Date().toISOString()}`,
    `//  tool version  : ${opts.toolVersion ?? "0.1.0"}`,
    "//",
    "//  这个文件只在第一次生成时由工具创建；之后的所有修改都由你掌控。",
    "//  · 字段 / bind() / onClickXxx 默认实现都在 .gen.ts 基类里",
    "//  · 在这里 override 任意 onClickXxx 即可写业务逻辑",
    "//  · 也可以加自定义字段 / 生命周期函数（onLoad / start / update ...）",
    "// =====================================================================",
    "",
    `import { _decorator } from "cc";`,
    `import { ${bindingsClass} } from ${JSON.stringify(importPath)};`,
    "",
    "const { ccclass } = _decorator;",
    "",
    `@ccclass("${viewClass}")`,
    `export class ${viewClass} extends ${bindingsClass} {`,
    "  // ---- override gen.ts 中已声明的 onClickXxx 钩子，添加业务逻辑即可 ----",
    "  // 例如：",
    "  //   protected onClickConfirmBtn(): void {",
    "  //     console.log(\"[view] confirm clicked\");",
    "  //   }",
    "",
    "  // ---- 也可以加自己需要的字段 / 生命周期 / 公共方法 ----",
    "  // start() {}",
    "  // update(dt: number) {}",
    "}",
    ""
  );
  return lines.join("\n");
}
